name: Test

on:
  - push
  - pull_request

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: test with ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        py: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.py }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.py }}
    - name: Install dependencies
      run: python -m pip install tox-gh>=1.2
    - name: Setup test suite
      run: tox -vv --notest
    - name: Run test suite
      run: tox --skip-pkg-install
